sudo: required
services:
  - docker

env:
  global:
    - IMAGE_NAME=journerist/drone-frontend

language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
on:
  branch: master

before_deploy:
- npm run build
- docker build --tag "${IMAGE_NAME}:latest" .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master